In [1]:
import numpy as np

In [4]:
array=[var for var in range(10)]

In [5]:
array

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
array=np.array(array)

In [8]:
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
array[4]

4

In [11]:
array=np.array(array,dtype=np.float32)

In [12]:
print(array)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [13]:
array.size

10

In [14]:
array.shape

(10,)

In [15]:
array.ndim

1

In [16]:
array.dtype

dtype('float32')

In [17]:
array[::-1]

array([9., 8., 7., 6., 5., 4., 3., 2., 1., 0.], dtype=float32)

In [39]:
a=[[1,2,3,4,5],
  [6,7,8,9,10],
  [11,12,13,14,15]]

In [40]:
a=np.array(a)

In [41]:
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [42]:
a[0::2,[1]]

array([[ 2],
       [12]])

In [49]:
a=[[[1,2,3,4,5],
  [6,7,8,9,10],
  [11,12,13,14,15]],
  [[1,2,3,4,5],
  [6,7,8,9,10],
  [11,12,13,14,15]],
  [[1,2,3,4,5],
  [6,7,8,9,10],
  [11,12,13,14,15]]]

In [54]:
print(a)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]


In [55]:
a[1::2,1::2,[3]]

array([[[9]]])

In [52]:
a=np.array(a)

In [53]:
a.shape

(3, 3, 5)

In [56]:
a.size

45

In [57]:
a.reshape(9,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [59]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])